language: node_js
install:
  - npm ci
  - npm install -g codecov
node_js:
  - 16
env:
  - DOCS_URL=https://github.com/DiegoVictor/cargo-terminal-api#errors-reference
  - APP_PORT=3333
script:
  - npm run test
  - codecov
