version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - app_network
  app:
    build: .
    depends_on:
      - mongodb
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    networks:
      - app_network
volumes:
  mongodata:
    driver: local
networks:
  app_network:
    driver: bridge
